import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import HeaderNavbar from "~/layouts.tsx/HeaderNavbar";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderNavbar />
      <main className="h-[100vh] w-full pt-[21.3rem]">
        <div>
          <iframe
            src="https://player.vimeo.com/video/796346595?h=8a4686b5aa&amp;controls=0&amp;loop=1&amp;background=1&amp;app_id=122963"
            frameBorder="0"
            allow="autoplay; fullscreen; picture-in-picture"
            allowFullScreen
            className="h-[87.5vh] w-full"
            data-ready="true"
          ></iframe>
        </div>
        <section>
          <header className="my-60">
            <h1 className="mx-auto max-w-4xl text-center text-6xl leading-[4.5rem]">
              We build connected brand systems from vision through execution
            </h1>
          </header>
          <div>
            <div>
              <div>
                <div></div>
                <div>
                  <p></p>
                  <button></button>
                </div>
              </div>
            </div>
            <div>
              <div>
                <div></div>
                <div>
                  <p></p>
                  <button></button>
                </div>
              </div>
            </div>
            <div>
              <div>
                <p></p>
                <button></button>
              </div>
            </div>
            <div>
              <div>
                <div>
                  <div></div>
                  <p></p>
                  <p></p>
                </div>
                <div>
                  <div></div>
                  <p></p>
                  <p></p>
                </div>
              </div>
            </div>
            <div>
              <div>
                <div></div>
                <div></div>
                <div></div>
              </div>
            </div>
          </div>
        </section>
        <div>
          <div>
            <p></p>
            <button></button>
          </div>
        </div>
      </main>
      <footer></footer>
    </>
  );
};

export default Home;
